services:
  db:
    image: postgres:16-alpine
    container_name: alerta-barrio-db
    environment:
      - POSTGRES_DB=alerta_barrio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d alerta_barrio"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alerta-barrio-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DOCKER_COMPOSE_ENABLED=false
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/alerta_barrio
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: