spring.application.name=ingsoft

Spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/alerta_barrio}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Deja que Springdoc maneje la redirección de manera estándar
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/api-docs

brevo.api.key=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
brevo.sender.email=juliancamilohah@gmail.com
brevo.sender.name=Alerta Barrio APP

spring.jackson.time-zone=America/Bogota